# fly.toml app configuration file generated for waka-next-orchestrator on 2024-03-23T10:41:25+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'waka-next-orchestrator'
primary_region = 'syd'

[build]
  dockerfile = "apps/orchestrator/Dockerfile"

[processes]
  app = "node index.js"
  admin = "sh -c 'WAKA_ORCHESTRATOR_NO_CACHE=true node index.js'"

[mounts]
  source = 'cache'
  destination = '/app/cache'
  processes = ['app']

[env]
  WAKA_ORCHESTRATOR_CACHE_PERIOD = "30000"
  WAKA_ORCHESTRATOR_CONFIG = """\
database:
  region: auto
  bucketName: waka-next
  publicUrl: https://static.waka.app
regions:
  zz-sample1:
    name: Sample Region
    gtfsZipUrl: https://next.waka.app/sample-feed-1.zip
  nz-akl:
    name: Auckland, New Zealand
    gtfsZipUrl: https://gtfs.at.govt.nz/gtfs.zip
"""

[[services]]
  processes = ['app']
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  processes = ['admin']
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 5000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
